name: ym_api_client
version: 1.0.0
description: OpenAPI API client
homepage: homepage

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  dio: '^5.2.0'
  equatable: '^2.0.5'
  json_annotation: '^4.4.0'

dev_dependencies:
  build_runner: any
  json_serializable: '^6.1.5'
  test: ^1.16.0
