targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        options:
          enable_cached_builds: true
        generate_for:
          - lib/core/presentation/pages/main/**/*.dart
          - lib/core/presentation/pages/screens/**/*.dart
          - lib/core/presentation/pages/tabs/**/*.dart
          - lib/features/**/presentation/*.dart
      auto_route_generator:auto_router_generator:
        options:
          enable_cached_builds: true
        generate_for:
          - lib/ui/route/route.dart
      freezed:
        options:
          enable_cached_builds: true
        generate_for:
          - lib/core/models/*.dart
          - lib/core/models/**/*.dart
          - lib/core/presentation/models/*.dart
          - lib/core/states/**/*.dart
          - lib/features/**/domain/*.dart
          - lib/features/**/presentation/bloc/*.dart
      riverpod_generator:
        enabled: true
        generate_for:
          include:
            - lib/core/providers/*.dart
            - lib/core/repositories/*.dart
            - lib/features/**/presentation/providers/*.dart
