targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        options:
          enable_cached_builds: true
        generate_for:
          - lib/ui/pages/main/**/*.dart
          - lib/ui/pages/screens/**/*.dart
          - lib/ui/pages/tabs/**/*.dart
          - lib/features/**/presentation/*.dart
      auto_route_generator:auto_router_generator:
        options:
          enable_cached_builds: true
        generate_for:
          - lib/ui/route/route.dart
      freezed:
        options:
          enable_cached_builds: true
        generate_for:
          - lib/data/states/**/*.dart
          - lib/data/models/**/*.dart
          - lib/data/models/*.dart
          - lib/data/model/ym/*.dart
          - lib/features/**/presentation/bloc/*.dart
          - lib/shared/bloc/*.dart
