generatorName: dart-dio
inputSpec: ym/v1/spec.yaml
outputDir: ym/v1/generated
enablePostProcessFile: true
additionalProperties:
  pubName: ym_api_client
  pubVersion: 1.0.0
  browserClient: false
  useEnumExtension: true
  sortModelPropertiesByRequiredFlag: false
  sortParamsByRequiredFlag: false
  # serializationLibrary: json_serializable
  # equalityCheckMethod: equatable
