openapi: 3.0.3
info:
  title: YagodMarket API
  version: 1.0.0
servers:
  - url: https://api.yagodmarket.ru/v1
paths:
  /adverts:
    get:
      summary: Список объявлений
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdvertsList"
components:
  schemas:
    Advert:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
      required:
        - id
        - title
